aaron:
  version: 1
  data-center-id: 2
  machine-id: 1

spring:
  application:
    name: user
  redis:
    database: 8
    host: 118.31.7.229
    port: 6379
    password: xym123
  datasource:
    url: jdbc:mysql://118.31.7.229:3307/user?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xym123

server:
  port: 8775
  servlet:
    context-path: /user
eureka:
  client:
    service-url:
      defaultZone: http://118.31.7.229:8761/eureka

  instance:
    prefer-ip-address: true
    # 这个是本服务的ip和端口
    #ip-address: 118.31.7.229
    ip-address: 192.168.1.101
    non-secure-port: 8775
